// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: batchEndpoints.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddWordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []*Word `protobuf:"bytes,1,rep,name=Words,proto3" json:"Words,omitempty"`
}

func (x *AddWordsRequest) Reset() {
	*x = AddWordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_batchEndpoints_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordsRequest) ProtoMessage() {}

func (x *AddWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_batchEndpoints_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordsRequest.ProtoReflect.Descriptor instead.
func (*AddWordsRequest) Descriptor() ([]byte, []int) {
	return file_batchEndpoints_proto_rawDescGZIP(), []int{0}
}

func (x *AddWordsRequest) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

type AddWordsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddWordsReply) Reset() {
	*x = AddWordsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_batchEndpoints_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWordsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordsReply) ProtoMessage() {}

func (x *AddWordsReply) ProtoReflect() protoreflect.Message {
	mi := &file_batchEndpoints_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordsReply.ProtoReflect.Descriptor instead.
func (*AddWordsReply) Descriptor() ([]byte, []int) {
	return file_batchEndpoints_proto_rawDescGZIP(), []int{1}
}

func (x *AddWordsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word         string            `protobuf:"bytes,1,opt,name=Word,proto3" json:"Word,omitempty"`
	Description  string            `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Translations map[string]string `protobuf:"bytes,3,rep,name=Translations,proto3" json:"Translations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_batchEndpoints_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_batchEndpoints_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_batchEndpoints_proto_rawDescGZIP(), []int{2}
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Word) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Word) GetTranslations() map[string]string {
	if x != nil {
		return x.Translations
	}
	return nil
}

var File_batchEndpoints_proto protoreflect.FileDescriptor

var file_batchEndpoints_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x61, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52,
	0x05, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xba, 0x01, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3b, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3f, 0x0a,
	0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x3e,
	0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e,
	0x0a, 0x08, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x10, 0x2e, 0x41, 0x64, 0x64,
	0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x41,
	0x64, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_batchEndpoints_proto_rawDescOnce sync.Once
	file_batchEndpoints_proto_rawDescData = file_batchEndpoints_proto_rawDesc
)

func file_batchEndpoints_proto_rawDescGZIP() []byte {
	file_batchEndpoints_proto_rawDescOnce.Do(func() {
		file_batchEndpoints_proto_rawDescData = protoimpl.X.CompressGZIP(file_batchEndpoints_proto_rawDescData)
	})
	return file_batchEndpoints_proto_rawDescData
}

var file_batchEndpoints_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_batchEndpoints_proto_goTypes = []interface{}{
	(*AddWordsRequest)(nil), // 0: AddWordsRequest
	(*AddWordsReply)(nil),   // 1: AddWordsReply
	(*Word)(nil),            // 2: Word
	nil,                     // 3: Word.TranslationsEntry
}
var file_batchEndpoints_proto_depIdxs = []int32{
	2, // 0: AddWordsRequest.Words:type_name -> Word
	3, // 1: Word.Translations:type_name -> Word.TranslationsEntry
	0, // 2: BatchService.AddWords:input_type -> AddWordsRequest
	1, // 3: BatchService.AddWords:output_type -> AddWordsReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_batchEndpoints_proto_init() }
func file_batchEndpoints_proto_init() {
	if File_batchEndpoints_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_batchEndpoints_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_batchEndpoints_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWordsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_batchEndpoints_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_batchEndpoints_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_batchEndpoints_proto_goTypes,
		DependencyIndexes: file_batchEndpoints_proto_depIdxs,
		MessageInfos:      file_batchEndpoints_proto_msgTypes,
	}.Build()
	File_batchEndpoints_proto = out.File
	file_batchEndpoints_proto_rawDesc = nil
	file_batchEndpoints_proto_goTypes = nil
	file_batchEndpoints_proto_depIdxs = nil
}
